### PR TITLE
Landing page added by Pascal

### PR DESCRIPTION
**Pull request by pascagihozo**
# Pull Request summary

This update introduces a new landing page, which allows users to select their laboratory immediately after logging in. Additionally, it modifies the "Result by Unit" page to prevent users from needing to re-select their laboratory, as this selection is now made on the landing page.

Please refer to the attached video for a detailed demonstration of these changes.

Best Regards,
Pascal Gihozo

## Screenshots
Screenshot from 2024-07-30 19-24-33
Screenshot from 2024-07-30 19-23-29
Screenshot from 2024-07-30 19-22-56
Screenshot from 2024-07-30 19-22-44

[Add relevant screenshots here if applicable]
[Screencast from 2024-07-30 19-21-14.webm](https://github.com/user-attachments/assets/752f8d85-444f-4146-af98-7895ce055dfc)

### CODE REVIEW

**Comment by pascagihozo** [comment]
new landing page, not yet styled

**Comment by mozzy11** [comment]
Hello @pascagihozo . Thanks for the PR.
Can you add a description of your changes and a screenshot , or screen recording of your changes ??

**Comment by pascagihozo** [comment]
These changes adds a new landing page which allows user to select laboratory directly after login. Second change is on Result by unit page it  prevents the user from re-selecting the laboratory because the user selects it at the landing page. Please check the video in the attachment for your reference

Best Regards,
Pascal GIHOZO
Screenshot from 2024-07-30 19-24-33
Screenshot from 2024-07-30 19-23-29
Screenshot from 2024-07-30 19-22-56
Screenshot from 2024-07-30 19-22-44
Screenshot from 2024-07-22 11-29-53
[Screencast from 2024-07-30 19-21-14.webm](https://github.com/user-attachments/assets/ec760a5c-a37d-49f1-a008-7bc288348667)

**Comment by pascagihozo** [comment]
Hello Moses,

I hope you are doing well. I have provided the screenshot of the new
changes but pull request haven't been merged yet. Would you please advise
on what to be done to resolve the conflicts?

Best Regards,
Pascal GIHOZO

**Comment by mozzy11** [comment]
Thanks @pascagihozo .
As per our call , we already have Result filters based on the user assigned Lab unit roles .
Can you create a separate PR to adress the IHC conclusions ??

**Pull request closed without merging**
