### PR TITLE
Add bread crumbs and common bread crumbs page

### PR DESCRIPTION
**Pull request by tendomart**
Hi @mozzy11  adding breadcrumb to 3 other pages. workplan, Pathology and ImmunohistochemistryDashboard pages

I have also added a resuable HomeBreadCrumb component, we can refactor alll the code, to avoid verbosity.

It has worked first with ImmunohistochemistryDashboard page

Screenshot from 2024-02-02 08-06-52
Screenshot from 2024-02-02 08-07-10
Screenshot from 2024-02-02 08-44-13

### CODE REVIEW

**Comment by mozzy11** [comment]
Thanks @tendomart . 
I like the reusable breadcrump . 
Can you make it more generic so that it can take a prop of an array of objects and generates a full hierarchy of breadcrumbs where its needed ?? you can leave there the default Home breadcrump
an example below of how it could be used. 
```
let breadcrup =[{ order=1 , link ="/"label="Home" } ,{ order=2 , link="/result" label="Result" } ] . 
<HomeBreadCrumb breadcrump={breadcrup}/>
```
That should render something like 
`Home/ Result`

**Comment by tendomart** [comment]
sure, will look into it.

**Comment by Agaba-derrick** [comment]
@tendomart  @mozzy11 have worked on these files and they are generic and render as per the above request mentioned by @mozzy11, I don't know if I should put a PR on it, I should have done it earlier if not for some errors in my environment.
Screenshot from 2024-02-04 23-43-25
Screenshot from 2024-02-04 23-43-44

**Comment by tendomart** [comment]
That's good @Agaba-derrick cool, you can share the PR and we compare .

**Pull request closed without merging**
