### PR TITLE
(#865): code coverage tool maven plugin

### PR DESCRIPTION
**Pull request by njiddasalifu**
# Pull Requests Requirements

- [x] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [x] The PR title follows conventional commit label standards.
- [x] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [x] The changes include tests or are validated by existing tests.
- [x] I have read and agree to the Contributing Guidelines of this project.

## Screenshots

[Add relevant screenshots here if applicable]

## Related Issue
[(https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/865)]

## Other
I prefer JaCoCo for the code coverage because it integrates easily with Maven, simplifying setup. It provides clear reports on line, method, and branch coverage, helping to ensure thorough testing.

### CODE REVIEW

**Comment by mozzy11** [comment]
Thanks @njiddasalifu . have you seen the [CI build failure](https://github.com/I-TECH-UW/OpenELIS-Global-2/actions/runs/11029732669/job/30959710391) ??

**Comment by njiddasalifu** [comment]
> Thanks @njiddasalifu . have you seen the [CI build failure](https://github.com/I-TECH-UW/OpenELIS-Global-2/actions/runs/11029732669/job/30959710391) ??

Yes @mozzy11 Looking at it, it had it run pass locally before pushing.

**Review by mozzy11 — CHANGES_REQUESTED** [review]
Thanks @njiddasalifu for this PR. 
did you have to delete the submodules ??

**Comment by njiddasalifu** [comment]
> Thanks @njiddasalifu for this PR. did you have to delete the submodules ??

No @mozzy11 I did not remove them. I did not take note of the change while pushing. I am sure it's the reason the CI is failing  
Just reverted just to the plugin req and CI is okay locally.

**Comment by mozzy11** [comment]
Thanks @njiddasalifu .
Can you see the [CI build failure](https://github.com/I-TECH-UW/OpenELIS-Global-2/actions/runs/11591133245/job/32270218758?pr=1269) ?

**Comment by Agaba-derrick** [comment]
@njiddasalifu  kindly do you mind sharing a video of this being tested locally

**Comment by njiddasalifu** [comment]
Hi @mozzy11 @Agaba-derrick  thanks for the review so far. 
Please kindly see some test failing logs on the pastbin link https://pastebin.com/sYXpFSpX

**Comment by mozzy11** [comment]
> Hi @mozzy11 @Agaba-derrick thanks for the review so far. Please kindly see some test failing logs on the pastbin link https://pastebin.com/sYXpFSpX

Your docker service is not started

**Comment by mozzy11** [comment]
By the way ive already worked on this issue here https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1298. We needed it urgently.
Thanks for attempting to work on it.
Can you pick another issue

**Pull request closed without merging**
