### PR TITLE
Implemented Rest Controller And created Re-useable Component for Config Menu Display and Edit

### PR DESCRIPTION
**Pull request by manishjha-04**
**> Solving issue**

- [x] #1012 

>**Recording**

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/84c99d3e-cc61-4c35-8dc3-5d00df303299

### CODE REVIEW

**Comment by manishjha-04** [comment]
Hey @mozzy11  its ready for review . Please let me know if any changes needed!

**Comment by manishjha-04** [comment]
Hey @mozzy11  in this i forgot only to implement printed report config will cover that too soon!

**Comment by mozzy11** [comment]
Thanks @manishjha-04 , Generally Looks good. 
Can you also add the  `printed report config `

**Review by mozzy11 — CHANGES_REQUESTED** [review]
Thanks @manishjha-04 for the grat work. 
Can we make the Page Titke dynamically change to reflect the current Configuration page being edited

**Comment by manishjha-04** [comment]
hey @mozzy11  i have updated the page title to change dynamically and yeah i will surely raise a new pr  soon for printed report config as you asked for !
 
**updated video:**

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/597535f5-d8b7-40ad-aaf0-06d9171f895f

**Review by mozzy11 — APPROVED** [review]

**Comment by adityadeshlahre** [comment]
### Latest changes seems broken not working for me !

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/132184385/05088e0e-2710-4874-b866-729b4c627b50

**Comment by manishjha-04** [comment]
Hey @adityadeshlahre have you recreated the containers?

**Comment by mozzy11** [comment]
@adityadeshlahre , this works fine for me and on the testing instance https://oe3.openelis-global.org/

**Comment by adityadeshlahre** [comment]
thank you @manishjha-04 

- force recreating container fixed the issue

**Pull request merged**
