### PR TITLE
Fixing rewriting test notification config menu page

### PR DESCRIPTION
**Pull request by adityadeshlahre**
- referencing #1051 
- fixing #1061

### WORKFLOW video soon

If any changes are required let me know :slightly_smiling_face: 
Thank You

### CODE REVIEW

**Comment by adityadeshlahre** [comment]
## WORKFLOW (testNotificationConfigMenu/Edit) pages

testNOTIFICATIONWorkFLOW

:slightly_smiling_face:

**Comment by mozzy11** [comment]
@adityadeshlahre is this ready for review ??
can you add a screen recording ??

**Review by mozzy11 — CHANGES_REQUESTED** [review]
@adityadeshlahre can you add a screen recording ??

**Comment by adityadeshlahre** [comment]
> @adityadeshlahre can you add a screen recording ??

https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1204#issuecomment-2254260735

In this comment there is workflow video already present its taking sometime to load !

**Pull request merged**
