### PR TITLE
(feat)Add missing translations to createpatientform

### PR DESCRIPTION
**Pull request by jona42-ui**
added some translations to the create patient form

### CODE REVIEW

**Comment by jona42-ui** [comment]
@mozzy11 kindly I will need your feeedback here such that I am sure to tackle all components
Thanks

**Comment by mozzy11** [comment]
Thanks @jona42-ui .
you would avoid too many formating changes for easy review

**Comment by jona42-ui** [comment]
Ooops! loking at my editor seeting its like I set prettier as default formarter in save
how can I go about this?

**Comment by jona42-ui** [comment]
or do we have specific formatting settings
sorry if I missed it

**Comment by mozzy11** [comment]
we have [eslint](https://github.com/I-TECH-UW/OpenELIS-Global-2/blob/2.8/frontend/package.json#L78-L79) for the frontend

but for easy review ignore the formating changes.

**Comment by jona42-ui** [comment]
ooh so i have to revert!

**Comment by mozzy11** [comment]
yeah , you need to revert the formating changes.

**Comment by jona42-ui** [comment]
wondering how, any quick hack pliz?

**Comment by mozzy11** [comment]
you can create a fresh PR if that would consume much time

**Pull request closed without merging**
