### PR TITLE
Added placeholder text to AddOrder.js

### PR DESCRIPTION
**Pull request by PR4NJ41**
Related PR #743
Solves Issue #738 
### Before
Screenshot from 2024-03-04 05-52-14

### After
Screenshot from 2024-03-04 05-51-28

### CODE REVIEW

**Review by sherrif10 — APPROVED** [review]
Looks good to me. You would combine this ticket to this  https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/743

**Review by codewithunknown — APPROVED** [review]

**Review by CalebSLane — CHANGES_REQUESTED** [review]
Text should use the internationalization functionality available by using `intl.formatMessage({})`, providing a message key, and placing the english value in en.json. We also support French (fr.json), but that can be added independently of this commit.

**Comment by mozzy11** [comment]
@PR4NJ41 , did you see @CalebSLane 's comment above ??

**Comment by PR4NJ41** [comment]
@mozzy11 Sir, I have made the required changes to my PR. Please review it. Thank You

**Pull request merged**
