### PR TITLE
Test Coverage: Modify Order Page

### PR DESCRIPTION
**Pull request by manishjha-04**
>**Solving issue #948**

Screenshot 2024-03-31 190634

**Recording**

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/d669c231-f55a-41a8-a1f8-f87f4c4c68df

### CODE REVIEW

**Comment by manishjha-04** [comment]
Hey @mozzy11 @abertnamanya  can you please review and let me know if anything extra  test or checks needed to be added in the workflow of modify order page!

**Comment by mozzy11** [comment]
Thanks @manishjha-04 , i can see some QA CI build tests are still failing

**Comment by manishjha-04** [comment]
Hello @mozzy11, I have specified the specification pattern. Please take a look now!

**Comment by mozzy11** [comment]
Thanks @manishjha-04 , I see its now the login test failing , can you fix that
see logs https://github.com/I-TECH-UW/OpenELIS-Global-2/actions/runs/8522369120/job/23342433811?pr=946

**Comment by mozzy11** [comment]
Thanks @manishjha-04 for the great work ,

**Review by mozzy11 — APPROVED** [review]

**Pull request merged**
