### PR TITLE
Add more integration tests to the Patient and Person service

### PR DESCRIPTION
**Pull request by josephbate**
# Pull Requests Requirements

- [x] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [x] The PR title follows conventional commit label standards.
- [ ] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [x] The changes include tests or are validated by existing tests.
- [x] I have read and agree to the Contributing Guidelines of this project.

## Summary
shifted the Cleanup method to `BaseWebContextSensitiveTest` avoid repitition 
added more test in the persion and patient service classes 

## Screenshots

[Add relevant screenshots here if applicable]

## Related Issue

[Add a link to the related issue or mention it here if applicable]

see: https://github.com/orgs/I-TECH-UW/projects/6/views/1?pane=issue&itemId=57668194

## Other

[Add any additional information or notes here]

### CODE REVIEW

**Comment by Agaba-derrick** [comment]
@josephbate  there is some ongoing work for this on [PR](https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1089) Which has been updated to this [PR ](https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/1160) , sugestion would be, if we can add Test on Patient Service !!

**Comment by mozzy11** [comment]
@josephbate , have you seen the merge conflicts ??

**Comment by josephbate** [comment]
does this fix it @mozzy11

**Comment by mozzy11** [comment]
@josephbate can you Look at this PR carefully ??

**Pull request closed without merging**
