### PR TITLE
Rewritten ARV Reports, EID Reports, VL Report, Intermediate Report and Special Request of Study Reports from jsp to react in New UI

### PR DESCRIPTION
**Pull request by manishjha-04**
Rewritten **_**all the versions of the above respective reports**_** in New UI !

**Additional Improvements Implemented:**
> Developed a versatile component to enhance code reusability."

**Issue** #741

**Before**:

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/dc6880ec-cc13-470d-9e30-72ec49df6017

**After:**

https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128405481/c0b98ac5-e416-48c0-ab4f-c7553ca8bc5e

### CODE REVIEW

**Comment by manishjha-04** [comment]
Hey @mozzy11, could you please review this? Also, for the remaining reports, I'll be submitting separate PRs to facilitate easier reviewing.

**Review by mherman22 — CHANGES_REQUESTED** [review]
Great work @manishjha-04 , i would still add breadcrumbs here!

**Comment by mozzy11** [comment]
@manishjha-04 , can you fix the merge conflicts ?

**Comment by manishjha-04** [comment]
Hey @mozzy11 I have resolved the merge conflicts! You can review it now !

**Review by mozzy11 — APPROVED** [review]

**Comment by mozzy11** [comment]
Thanks @manishjha-04

**Pull request merged**
