### PR TITLE
(add) Documentation for new contributors to easily get started

### PR DESCRIPTION
**Pull request by valens200**
# Pull Requests Requirements

## Summary

Getting Started [Guide](https://demo.hedgedoc.org/0pwgkbPGTUGEbGmdzqBa6A) for onboarding GSoC'24 prospective contributors in openElis Global 2.

We understand how painful it might be for new onboarding contributors to get started with OpenElis Global 2, As the project continues to evolve, it’s essential to ensure that our documentation remains up-to-date and accessible. We understand that navigating a new project can be challenging, especially for prospective contributors. Therefore, this documentation serves as a central hub for all information related to our project, making it easier for newcomers to get started.

You can preview the documentation by clicking [here](https://demo.hedgedoc.org/0pwgkbPGTUGEbGmdzqBa6A)
## Screenshots

Screen Shot 2024-03-21 at 18 15 17

### CODE REVIEW

**Comment by valens200** [comment]
@mozzy11 @sherrif10 you can please take a review on this.
Thank you!

**Comment by valens200** [comment]
@sherrif10 @mherman22 @mozzy11 , you can also review this ticket.

**Comment by mozzy11** [comment]
Thabks @valens200 . 
If youre still intrested in this , we should move Documenetation to our [wiki ](https://uwdigi.atlassian.net/wiki/spaces/OG/overview)in JIRA

**Comment by valens200** [comment]
sure @mozzy11 please do it! I'm still interested.

**Pull request closed without merging**
