### PR TITLE
Rewrite the PrintBarcode page in React

### PR DESCRIPTION
**Pull request by rahul6603**
This PR aims to enhance the user experience and maintainability of the [PrintBarcode](https://openelis28.openelis-global.org/api/OpenELIS-Global/PrintBarcode) page by rewriting it in React and implementing a REST controller while keeping the existing logic.

Issue - https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/701

### CODE REVIEW

**Comment by rahul6603** [comment]
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128216878/58474082-4463-4517-b26c-fd4058ecf1b2

**Comment by rahul6603** [comment]
Hey @mozzy11 !
I have created this WIP PR with the initial frontend changes, let me know if any changes are required so I can proceed further.
Thanks.

**Comment by mozzy11** [comment]
Thanks @rahul6603 
Generally Looks good.  you can go ahed

**Comment by rahul6603** [comment]
Hi @mozzy11 , I have completed the remaining changes required for displaying the barcodes. I have attached the testing video below.
I didn't need to create a new REST controller, as we already have APIs for the logic the old JSP controller has and I am directly invoking those APIs in the react code.
Could you please review the changes and let me know if any changes are required.
Thank you.

**Comment by rahul6603** [comment]
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/128216878/5a606c0d-b17e-4e05-81dc-d3093c46ff6d

**Review by mozzy11 — APPROVED** [review]

**Pull request merged**
