### PR TITLE
Create Spring and Hibernate test Context for the intergration tests #283

### PR DESCRIPTION
**Pull request by mozzy11**
I have tried to set up the actual Spring and HIbernate Context for the sample integration tests , and a little of mocking some some services.
Am also running this against the actual Postgress database managed by testContainers in order to have a testing enviroment that simulates the real runtime  enviroment

### CODE REVIEW

**Comment by mozzy11** [comment]
hi @caseyi @CalebSLane ,
can you look at this PR.
i was basically setting up Spring and Hibernate Test Context for the Intergration tests , also added some basic tests for the Patient and Person services .
it could serve as a basis for adding more Integration tests for the service layer

**Comment by mozzy11** [comment]
cc @caseyi @CalebSLane

**Review by CalebSLane — APPROVED** [review]
These changes should not impact normal function of OE

**Comment by mozzy11** [comment]
Thanks @CalebSLane ,
these are entirely just tests

**Pull request merged**
