### PR TITLE
Update order entry page

### PR DESCRIPTION
**Pull request by mozzy11**
Refactor Order Entry page to dispay test per sample added
https://docs.google.com/document/d/1ixH5_MGXJI4TKj20g0ZQsB-393jbUy7N/edit

### CODE REVIEW

**Comment by mozzy11** [comment]
image

**Comment by CalebSLane** [comment]
@caseyi do we still want the select option to self erase once a selection is made, or remember the option that is currently selected? The previous option was done to allow multiple selections to be made, but since we spawn a new select for every sample it is no longer required

**Comment by CalebSLane** [comment]
additionally, when removing a sample, it clears out the content of the div, but there's nothing to delete that div wholesale. 
sampleSelects
is this the desired functionality?

**Review by CalebSLane — CHANGES_REQUESTED** [review]
seeing 2 instances of form:hidden path="sampleXML". Is this needed?

**Comment by mozzy11** [comment]
> seeing 2 instances of form:hidden path="sampleXML". Is this needed?
I moved the `form:hidden path="sampleXML`from the `sampleAdd.jsp file` to avoid making it repeated several times and put it directly in the` samplePatientEntry.jsp` . That means `sampleEdit.jsp` no longer inherits it ,so i have to add it there too

**Comment by mozzy11** [comment]
@CalebSLane ,
Pushed commit for
- Select sample should remeber selected Oprion
- Remove sample should clear out the entire sample Block

image

**Pull request merged**
