### PR TITLE
made the search bar responsive

### PR DESCRIPTION
**Pull request by Bahati308**
# Pull Requests Requirements

- [ ] The PR title includes a brief description of the work done, including the
      Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [ ] The PR title follows conventional commit label standards.
- [ ] The changes confirm to the OpenElis Global x3 Styleguide and design
      documentation.
- [ ] The changes include tests or are validated by existing tests.
- [ ] I have read and agree to the Contributing Guidelines of this project.

## Screenshots

[Add relevant screenshots here if applicable]

## Related Issue

[Add a link to the related issue or mention it here if applicable]

## Other

[Add any additional information or notes here]

### CODE REVIEW

**Comment by mozzy11** [comment]
Thanks @Bahati308 ,
can you add screenshots or a screen recording ??

**Comment by Bahati308** [comment]
here is an attachment sir, @mozzy11 
Screenshot from 2024-09-12 19-38-42

**Comment by Bahati308** [comment]
I put the search bar slightly below the banner for clarity(to make the banner visible )

**Comment by Bahati308** [comment]
I put the search bar slightly below the banner for clarity(to make the banner visible )

**Review by mozzy11 — CHANGES_REQUESTED** [review]
Thanks @Bahati308 .
Can you make the blue search bar strecth up to the left border like here
image

**Comment by Bahati308** [comment]
thanks @mozzy11, why not, lemme go ahead and do it.

**Comment by Bahati308** [comment]
hello @mozzy11 , here are the required changes attended to as requested. 

Screenshot from 2024-11-01 16-28-23

Screenshot from 2024-11-01 16-29-00

Screenshot from 2024-11-01 16-29-32

**Review by mozzy11 — CHANGES_REQUESTED** [review]
Thanks @Bahati308 ,
Can you adde a few Patients in your instace and attach the screen shot with a few patient Results ??

**Comment by Bahati308** [comment]
okay, sir here are the findings. 
Screenshot from 2024-11-06 20-24-50
Screenshot from 2024-11-06 20-25-38

**Comment by mozzy11** [comment]
i cant view the screen shots

**Comment by mozzy11** [comment]
Thanks @Bahati308 

can you try to replicate some thing like this 

image

image


image

The results page should always vertically allign with the search bar

**Comment by Bahati308** [comment]
Okay, lemme go for it

**Comment by Bahati308** [comment]
thanks for the advise sir, here are the screenshots to backup the modifications made 
Screenshot from 2024-11-06 21-45-32
Screenshot from 2024-11-06 21-46-03
Screenshot from 2024-11-06 21-46-17

**Comment by mozzy11** [comment]
Thanks @Bahati308

**Comment by Bahati308** [comment]
welcome @mozzy11 , thanks for your help

**Pull request merged**
