### PR TITLE
location:Make Geo fields customizable

### PR DESCRIPTION
**Pull request by gitcliff**

### CODE REVIEW

**Review by CalebSLane — COMMENTED** [review]
hi @gitcliff, is there a file missing from this PR? How are these DB values supposed to appear in the front end on the patient management screen for example? Or is that still coming?

**Comment by gitcliff** [comment]
hello @CalebSLane here is a screen shot for the DB values in the front end 
Screenshot from 2022-04-09 23-37-27
https://docs.google.com/document/d/1nDpKQQy7SI_19VhDISBgKJ4cWb3b3yOt/edit

**Comment by CalebSLane** [comment]
yes, but are these values supposed to show up on the order entry/patient management screen as the labels?

**Comment by gitcliff** [comment]
hello @CalebSLane i have fixed it 
Thanks

**Review by CalebSLane — APPROVED** [review]

**Pull request merged**
