### PR TITLE
Rewriting activity Report into New React UI

### PR DESCRIPTION
**Pull request by sherrif10**
# Pull Requests Requirements

- [ ] The PR title includes a brief description of the work done, including the Issue number if applicable.
- [ ] The PR includes a video showing the changes for the work done.
- [ ] The PR title follows conventional commit label standards.
- [ ] The changes confirm to the OpenElis Global x3 Styleguide and design documentation.
- [ ] The changes include tests or are validated by existing tests.
- [ ] I have read and agree to the Contributing Guidelines of this project.

## Screenshots

[Add relevant screenshots here if applicable]

## Related Issue

[Add a link to the related issue or mention it here if applicable]
https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/758
## Other

[Add any additional information or notes here]
This PR should capture all the recent reviews, one only pending review that i see its quite remaining is having all the one component but rendering these threee reports based on type.  @mozzy11

### CODE REVIEW

**Comment by sherrif10** [comment]
This is WIP

**Comment by sherrif10** [comment]
Am going to refactor this three components into one single component , with in  that component, there should be a selector button that first selects report by type either by test or panel. then if any report is selected, the that report panel page should be rendered. Ideally we should have all the three reports but show only one generic report which should act as a parent of all those reports. cc @mozzy11

**Comment by sherrif10** [comment]
https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/48015736/e1a85987-bfe7-4f2b-be6f-c2837786e80e

cc @mozzy11 Let me know what you think

**Comment by mozzy11** [comment]
Thanks @sherrif10 for working on this . 
THis report has been worked on in this PR https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/980

**Pull request closed without merging**
