### PR TITLE
Fix/id validation notifications

### PR DESCRIPTION
**Pull request by sayed4900**
fixes : https://github.com/I-TECH-UW/OpenELIS-Global-2/issues/707

this pull request to Fix Patient ID Validation Notification Popups
[Screencast from 03-21-2024 03:38:22 AM.webm](https://github.com/I-TECH-UW/OpenELIS-Global-2/assets/103145317/350b979f-397f-4eea-bc03-e76e8b1d5335)

### CODE REVIEW

**Comment by sayed4900** [comment]
@mozzy11 can you review the last commit? 
sorry about adding the tests code, I don't know how they added.

**Review by mozzy11 — APPROVED** [review]
Thanks @sayed4900 .
Can keep the API Tests in a separate PR and only leave the changes for this PR ??

**Review by mozzy11 — CHANGES_REQUESTED** [review]
Thanks @sayed4900 .
Can keep the API Tests in a separate PR and only leave the changes for this PR ??

**Comment by sayed4900** [comment]
> Thanks @sayed4900 . Can keep the API Tests in a separate PR and only leave the changes for this PR ??
Thankks @mozzy11.
I delete tests from this branch and there is a different PR with them [here](https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/793).
I apologize for this error.

**Comment by mozzy11** [comment]
@sayed4900 can you see the build failure https://github.com/I-TECH-UW/OpenELIS-Global-2/actions/runs/8374564100/job/22930096382?pr=853

**Comment by sayed4900** [comment]
> @sayed4900 can you add a screenshot or screenrecording of your fix ??

I upload short video on description that show my fix, here it is
[Uploading Screencast from 03-21-2024 03:38:22 AM.webm…]()

**Comment by sayed4900** [comment]
> > Thanks @sayed4900 . Can keep the API Tests in a separate PR and only leave the changes for this PR ??
> > Thankks @mozzy11.
> > I delete tests from this branch and there is a different PR with them [here](https://github.com/I-TECH-UW/OpenELIS-Global-2/pull/793).
> > I apologize for this error.



> @sayed4900 can you see the build failure https://github.com/I-TECH-UW/OpenELIS-Global-2/actions/runs/8374564100/job/22930096382?pr=853
@mozzy11 
Actually, I don't know how to solve this problem. Can you show me the way and I can get started right away?

**Comment by sayed4900** [comment]
@mozzy11 is there anything should I do to enable merge this PR?

**Review by mozzy11 — APPROVED** [review]

**Pull request merged**
