### PR TITLE
Adding ReferenceTableService test

### PR DESCRIPTION
**Pull request by valens200**
# ReferenceTableService test

## Summary

With the purpose of the system's quality assurance, I added this ReferenceTablesTest just to ensure that the class is doing its job.

### CODE REVIEW

**Review by mherman22 — COMMENTED** [review]
Are all these changes necessary for adding **ReferenceTableServiceTest**?

**Comment by sherrif10** [comment]
To add on the voice of @mherman22  ,You might need to close this ticket and open a clean one

**Comment by valens200** [comment]
Thank you @mherman22  and @sherrif10. Let me close this ticket and open a clean one. 
 I don’t know why these changes are being added to my PR. Before pushing, I am pulling from the main branch ’ develop_3x ' branch and I think those changes have been made by others, not by me. I don’t know whether I can stop pulling from the main branch ' develop_3x ' before pushing to my branch to prevent this.

**Comment by mherman22** [comment]
> Thank you @mherman22 and @sherrif10. Let me close this ticket and open a clean one. I don’t know why these changes are being added to my PR. Before pushing, I am pulling from the main branch ’ develop_3x ' branch and I think those changes have been made by others, not by me. I don’t know whether I can stop pulling from the main branch ' develop_3x ' before pushing to my branch to prevent this.

You are making changes on the develop2x branch and trying to merge on develop_3x branch. Those two branches are different. They are 226 commits apart

**Comment by mherman22** [comment]
> Thank you @mherman22 and @sherrif10. Let me close this ticket and open a clean one. I don’t know why these changes are being added to my PR. Before pushing, I am pulling from the main branch ’ develop_3x ' branch and I think those changes have been made by others, not by me. I don’t know whether I can stop pulling from the main branch ' develop_3x ' before pushing to my branch to prevent this.

did you do `git pull --rebase upstream develop_3x` before pushing?

**Pull request closed without merging**
